language: go

go:
  - "1.x"
  - "1.8"
  - "1.10.x"
  - master

install: true

before_script:
  - go get github.com/go-sql-driver/mysql
  - go get github.com/go-xorm/xorm
  - go get github.com/go-xorm/builder 
  - go get github.com/go-xorm/core
  - go get github.com/jasonlvhit/gocron 
  - go get github.com/jinzhu/now 
  - go get github.com/chai2010/gettext-go 
  - go get github.com/satori/go.uuid 