language: go

go:
  - "1.x"
  - "1.8"
  - "1.10.x"
  - master

install: true

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - export GOPATH=`pwd`
  - chmod +x make.sh

script:
  - ./make.sh build
  - ./make.sh build_mods
